name: Release Workflow
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [windows, darwin, linux]
        exclude:
          - arch: arm64
            os: linux # Remove arm64-linux has issues with gofitz
      fail-fast: false
    runs-on: ${{ fromJson('{"windows":"windows-latest","darwin":"macos-latest","linux":"ubuntu-latest"}')[matrix.os] }}
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      ZIG_ARCH: ${{ fromJson('{"arm64":"aarch64","amd64":"x86_64"}')[matrix.arch] }}
      ZIG_OS: ${{ fromJson('{"linux":"linux-gnu","darwin":"linux-musl","windows":"windows-gnu"}')[matrix.os] }}
      CGO_ENABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          
      - name: Set up Zig (only for linux and windows on arm64)
        if: ${{ matrix.arch == 'arm64' && (matrix.os == 'linux' || matrix.os == 'windows') }}
        uses: mlugg/setup-zig@v2
        with:
          version: master
          
      - name: Build Binary With Zig (for linux or windows on arm64)
        shell: bash
        if: ${{ matrix.arch == 'arm64' && (matrix.os == 'linux' || matrix.os == 'windows') }}
        run: |
          CC="zig cc -target ${{ env.ZIG_ARCH }}-${{ env.ZIG_OS }}" \
          go build -ldflags="-s -w" -o gowall${{ matrix.os == 'windows' && '.exe' || '' }}
          
      - name: Build Binary Without Zig (for other targets)
        shell: bash
        if: ${{ matrix.arch == 'amd64' || (matrix.arch =='arm64' && matrix.os == 'darwin') }}
        run: |
          go build -ldflags="-s -w" -o gowall${{ matrix.os == 'windows' && '.exe' || '' }}
          
      - name: Create zip archive
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            zip gowall-${{ matrix.arch }}-${{ matrix.os }}.zip gowall.exe
          else
            zip gowall-${{ matrix.arch }}-${{ matrix.os }}.zip gowall
          fi
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gowall-${{env.GOARCH}}-${{env.GOOS}}
          path: gowall-${{ matrix.arch }}-${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: Create zip files and upload
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for dir in ./artifacts/*/; do
            if [ -d "$dir" ]; then
              for file in "$dir"*.zip; do
                if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  echo "Uploading $filename"
                  gh release upload ${{ github.ref_name }} "$file" --clobber
                fi
              done
            fi
          done